<?php

namespace AppLas\AppLasSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObiektRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObiektRepository extends EntityRepository
{
}
