<?php

namespace AppLas\AppLasSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PunktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PunktRepository extends EntityRepository {

    public function findAllOrderedByName() {
        return $this->getEntityManager()
                        ->createQuery('SELECT p FROM AcmeStoreBundle:Product p ORDER BY p.name ASC')
                        ->getResult();
    }
}
