<?php

namespace AppLas\AppLasSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WarstwaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarstwaRepository extends EntityRepository
{
}
